#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jdk-slf4j
Version  : 1.7.21
Release  : 1
URL      : http://www.slf4j.org/dist/slf4j-1.7.21.tar.gz
Source0  : http://www.slf4j.org/dist/slf4j-1.7.21.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: jdk-slf4j-data
BuildRequires : apache-ant
BuildRequires : apache-maven
BuildRequires : apache-maven2
BuildRequires : javapackages-tools
BuildRequires : jdk-aether
BuildRequires : jdk-aopalliance
BuildRequires : jdk-atinject
BuildRequires : jdk-bsh
BuildRequires : jdk-build-helper-maven-plugin
BuildRequires : jdk-cal10n
BuildRequires : jdk-cdi-api
BuildRequires : jdk-commons-cli
BuildRequires : jdk-commons-codec
BuildRequires : jdk-commons-collections
BuildRequires : jdk-commons-compress
BuildRequires : jdk-commons-io
BuildRequires : jdk-commons-lang
BuildRequires : jdk-commons-lang3
BuildRequires : jdk-commons-logging
BuildRequires : jdk-doxia
BuildRequires : jdk-doxia-sitetools
BuildRequires : jdk-guava
BuildRequires : jdk-guice
BuildRequires : jdk-httpcomponents-client
BuildRequires : jdk-httpcomponents-core
BuildRequires : jdk-javassist
BuildRequires : jdk-jsoup
BuildRequires : jdk-jsr-305
BuildRequires : jdk-log4j
BuildRequires : jdk-log4j1.2
BuildRequires : jdk-maven-antrun-plugin
BuildRequires : jdk-maven-archiver
BuildRequires : jdk-maven-common-artifact-filters
BuildRequires : jdk-maven-compiler-plugin
BuildRequires : jdk-maven-filtering
BuildRequires : jdk-maven-invoker
BuildRequires : jdk-maven-jar-plugin
BuildRequires : jdk-maven-javadoc-plugin
BuildRequires : jdk-maven-plugin-tools
BuildRequires : jdk-maven-reporting-api
BuildRequires : jdk-maven-resources-plugin
BuildRequires : jdk-maven-shared-incremental
BuildRequires : jdk-maven-shared-utils
BuildRequires : jdk-objectweb-asm
BuildRequires : jdk-plexus-archiver
BuildRequires : jdk-plexus-build-api
BuildRequires : jdk-plexus-cipher
BuildRequires : jdk-plexus-classworlds
BuildRequires : jdk-plexus-compiler
BuildRequires : jdk-plexus-containers
BuildRequires : jdk-plexus-i18n
BuildRequires : jdk-plexus-interactivity
BuildRequires : jdk-plexus-interpolation
BuildRequires : jdk-plexus-io
BuildRequires : jdk-plexus-sec-dispatcher
BuildRequires : jdk-plexus-utils
BuildRequires : jdk-plexus-velocity
BuildRequires : jdk-sisu
BuildRequires : jdk-slf4j
BuildRequires : jdk-snappy-java
BuildRequires : jdk-surefire
BuildRequires : jdk-velocity
BuildRequires : jdk-wagon
BuildRequires : jdk-xbean
BuildRequires : jdk-xmlunit
BuildRequires : lxml
BuildRequires : openjdk-dev
BuildRequires : python3
BuildRequires : six
BuildRequires : xmvn

%description
# About SLF4J
The Simple Logging Facade for Java (SLF4J) serves as a simple facade or abstraction for various logging frameworks (e.g. java.util.logging, logback, log4j) allowing the end user to plug in the desired logging framework at deployment time.
More information can be found on the [SLF4J website](http://www.slf4j.org).
# Build Status
[![Build Status](https://travis-ci.org/qos-ch/slf4j.png)](https://travis-ci.org/qos-ch/slf4j)

%package data
Summary: data components for the jdk-slf4j package.
Group: Data

%description data
data components for the jdk-slf4j package.


%prep
%setup -q -n slf4j-1.7.21

find . -name "*.jar" | xargs rm
python3 /usr/share/java-utils/pom_editor.py pom_disable_module integration
python3 /usr/share/java-utils/pom_editor.py pom_disable_module osgi-over-slf4j
python3 /usr/share/java-utils/pom_editor.py pom_disable_module slf4j-android
python3 /usr/share/java-utils/pom_editor.py pom_disable_module slf4j-migrator
python3 /usr/share/java-utils/pom_editor.py pom_remove_plugin :maven-source-plugin
python3 /usr/share/java-utils/pom_editor.py pom_xpath_inject "pom:project/pom:properties" "
<project.build.sourceEncoding>ISO-8859-1</project.build.sourceEncoding>"
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove "pom:links"
python3 /usr/share/java-utils/pom_editor.py pom_xpath_inject "pom:plugin[pom:artifactId[text()='maven-javadoc-plugin']]/pom:configuration" "
<detectJavaApiLink>false</detectJavaApiLink>
<isOffline>false</isOffline>
<links><link>/usr/share/javadoc/java</link></links>"
find -name "*.css" -o -name "*.js" -o -name "*.txt" | \
xargs -t /usr/bin/perl -pi -e 's/\r$//g'
python3 /usr/share/java-utils/pom_editor.py pom_xpath_remove   pom:extensions
python3 /usr/share/java-utils/pom_editor.py pom_xpath_inject "pom:plugin[pom:artifactId='maven-jar-plugin']/pom:executions" "
<execution>
<id>default-jar</id>
<phase>skip</phase>
</execution>" slf4j-api
python3 /usr/share/java-utils/mvn_package.py :slf4j-parent __noinstall
python3 /usr/share/java-utils/mvn_package.py :slf4j-site __noinstall
python3 /usr/share/java-utils/mvn_package.py :slf4j-api
python3 /usr/share/java-utils/mvn_package.py :slf4j-simple
python3 /usr/share/java-utils/mvn_package.py :slf4j-nop

%build
python3 /usr/share/java-utils/mvn_build.py -f -s

%install
xmvn-install  -R .xmvn-reactor -n slf4j -d %{buildroot}

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/slf4j/jcl-over-slf4j.jar
/usr/share/java/slf4j/jul-to-slf4j.jar
/usr/share/java/slf4j/log4j-over-slf4j.jar
/usr/share/java/slf4j/slf4j-api.jar
/usr/share/java/slf4j/slf4j-ext.jar
/usr/share/java/slf4j/slf4j-jcl.jar
/usr/share/java/slf4j/slf4j-jdk14.jar
/usr/share/java/slf4j/slf4j-log4j12.jar
/usr/share/java/slf4j/slf4j-nop.jar
/usr/share/java/slf4j/slf4j-simple.jar
/usr/share/maven-metadata/slf4j-jcl-over-slf4j.xml
/usr/share/maven-metadata/slf4j-jul-to-slf4j.xml
/usr/share/maven-metadata/slf4j-log4j-over-slf4j.xml
/usr/share/maven-metadata/slf4j-slf4j-ext.xml
/usr/share/maven-metadata/slf4j-slf4j-jcl.xml
/usr/share/maven-metadata/slf4j-slf4j-jdk14.xml
/usr/share/maven-metadata/slf4j-slf4j-log4j12.xml
/usr/share/maven-metadata/slf4j.xml
/usr/share/maven-poms/slf4j/jcl-over-slf4j.pom
/usr/share/maven-poms/slf4j/jul-to-slf4j.pom
/usr/share/maven-poms/slf4j/log4j-over-slf4j.pom
/usr/share/maven-poms/slf4j/slf4j-api.pom
/usr/share/maven-poms/slf4j/slf4j-ext.pom
/usr/share/maven-poms/slf4j/slf4j-jcl.pom
/usr/share/maven-poms/slf4j/slf4j-jdk14.pom
/usr/share/maven-poms/slf4j/slf4j-log4j12.pom
/usr/share/maven-poms/slf4j/slf4j-nop.pom
/usr/share/maven-poms/slf4j/slf4j-simple.pom
